# apt-add-repository
# Autogenerated from man page /usr/share/man/man1/apt-add-repository.1.gz
complete -c apt-add-repository -s h -l help --description 'Show help message and exit.'
complete -c apt-add-repository -s m -l massive-debug --description 'Print a lot of debug information to the command line.'
complete -c apt-add-repository -s r -l remove --description 'Remove the specified repository.'
complete -c apt-add-repository -s y -l yes --description 'Assume yes to all queries.'
complete -c apt-add-repository -s u -l update --description 'After adding the repository, update the package cache with packages from this…'
complete -c apt-add-repository -s k -l keyserver --description 'Use a custom keyserver URL instead of the default.'
complete -c apt-add-repository -s s -l enable-source --description 'Allow downloading of the source packages from the repository REPOSITORY STRIN…'

