# bluetooth-sendto
# Autogenerated from man page /usr/share/man/man1/bluetooth-sendto.1.gz
complete -c bluetooth-sendto -l device --description 'Define the device address to send the file(s) to.'
complete -c bluetooth-sendto -l name --description 'Define the device name to send the file(s) to.'

