# bsd-from
# Autogenerated from man page /usr/share/man/man1/bsd-from.1.gz
complete -c bsd-from -s c --description 'Just print a count of messages and exit.'
complete -c bsd-from -s f --description 'The supplied file is examined instead of the invoker\'s mailbox.'
complete -c bsd-from -s s --description 'Only mail from addresses containing the supplied string are printed.'

