# calendar
# Autogenerated from man page /usr/share/man/man1/calendar.1.gz
complete -c calendar -s A --description 'Print lines from today and next num days (forward, future).  Defaults to one.'
complete -c calendar -s a --description 'Process the calendar files of all users and mail the results to them.'
complete -c calendar -s B --description 'Print lines from today and previous num days (backward, past).'
complete -c calendar -s b --description 'Enforce special date calculation mode for Cyrillic calendars.'
complete -c calendar -s l --description 'Print lines from today and next num days (forward, future).  Defaults to one.'
complete -c calendar -s e --description 'Print lines from today and next num days, only if today is Friday (forward, f…'
complete -c calendar -s f --description 'Use calendarfile as the default calendar file.'
complete -c calendar -s t --description 'Act like the specified value is today instead of using the current date.'
complete -c calendar -s w --description 'Print day of the week name in front of each event.'

