# cjet
# Autogenerated from man page /usr/share/man/man1/cjet.1.gz
complete -c cjet -s h --description 'Show summary of options.'
complete -c cjet -s f --description 'Use full paint mode instead of partial paint mode.'
complete -c cjet -s p --description 'Ignore paper size commands.'
complete -c cjet -s q --description 'Quiet mode.  Suppresses all warning messages.'
complete -c cjet -s x --description 'Shift output on paper by X dots horizontally.'
complete -c cjet -s y --description 'Shift output on paper by Y dots vertically.'

