# col
# Autogenerated from man page /usr/share/man/man1/col.1.gz
complete -c col -s b --description 'Do not output any backspaces, printing only the last character written to eac…'
complete -c col -s f --description 'Forward half line feeds are permitted (``fine\'\' mode).'
complete -c col -s h --description 'Do not output multiple spaces instead of tabs (default).'
complete -c col -s l --description 'Buffer at least num lines in memory.  By default, 128 lines are buffered.'
complete -c col -s p --description 'Force unknown control sequences to be passed through unchanged.'
complete -c col -s x --description 'Output multiple spaces instead of tabs.'

