# column
# Autogenerated from man page /usr/share/man/man1/column.1.gz
complete -c column -s c --description 'Output is formatted for a display columns wide.'
complete -c column -s s --description 'Specify a set of characters to be used to delimit columns for the t option.'
complete -c column -s t --description 'Determine the number of columns the input contains and create a table.'
complete -c column -s x --description 'Fill columns before filling rows.'
complete -c column -s n --description 'By default, the column command will merge multiple adjacent delimiters into a…'
complete -c column -s e --description 'Do not ignore empty lines.'

