# dpkg-vendor
# Autogenerated from man page /usr/share/man/man1/dpkg-vendor.1.gz
complete -c dpkg-vendor -l is --description 'Exits with 0 if the current vendor is vendor.  Otherwise exits with 1.'
complete -c dpkg-vendor -l derives-from --description 'Exits with 0 if the current vendor distribution is a derivative of vendor, ot…'
complete -c dpkg-vendor -l query --description 'Print on standard output the value of the vendor-specific field for the curre…'
complete -c dpkg-vendor -l help --description 'Show the usage message and exit.'
complete -c dpkg-vendor -l version --description 'Show the version and exit.'
complete -c dpkg-vendor -l vendor --description 'Assumes the current vendor is vendor instead of discovering it with the DEB_V…'

