# dpkg-statoverride
# Autogenerated from man page /usr/share/man/man1/dpkg-statoverride.1.gz
complete -c dpkg-statoverride -l admindir --description 'Set the administrative directory to directory.'
complete -c dpkg-statoverride -l instdir --description 'Set the installation directory, which refers to the directory where packages …'
complete -c dpkg-statoverride -l root --description 'Set the root directory to directory, which sets the installation directory to…'
complete -c dpkg-statoverride -l force-things --description 'TQ  --no-force-things ", " --refuse-things Force or refuse (no-force and refu…'
complete -c dpkg-statoverride -l force --description 'Force an action, even if a sanity check would otherwise prohibit it.'
complete -c dpkg-statoverride -l update --description 'Immediately try to change the path to the new owner and mode if it exists.'
complete -c dpkg-statoverride -l add --description 'Add an override for path.'
complete -c dpkg-statoverride -l remove --description 'Remove an override for path, the status of path is left unchanged by this com…'
complete -c dpkg-statoverride -l list --description 'List all overrides.'
complete -c dpkg-statoverride -l help --description 'Show the usage message and exit.'
complete -c dpkg-statoverride -l force-help --description 'Give help about the --force-thing options (since dpkg 1. 19. 5).'
complete -c dpkg-statoverride -l version --description 'Show the version and exit.'
complete -c dpkg-statoverride -l no-force-things -l refuse-things --description 'Force or refuse (no-force and refuse mean the same thing) to do some things (…'
complete -c dpkg-statoverride -l force-all --description '.'
complete -c dpkg-statoverride -l quiet --description 'Be less verbose about what we do.'

