# dpkg-genbuildinfo
# Autogenerated from man page /usr/share/man/man1/dpkg-genbuildinfo.1.gz
complete -c dpkg-genbuildinfo -l build --description 'Specifies the build type from a comma-separated list of components.'
complete -c dpkg-genbuildinfo -s c --description 'Specifies the main source control file to read information from.'
complete -c dpkg-genbuildinfo -s l --description 'Specifies the changelog file to read information from.'
complete -c dpkg-genbuildinfo -s f --description 'Specifies where is the list of files that have been produced by the build, ra…'
complete -c dpkg-genbuildinfo -s F --description 'Specifies the format of the changelog.'
complete -c dpkg-genbuildinfo -s O --description 'Print the buildinfo file to standard output (or filename if specified) rather…'
complete -c dpkg-genbuildinfo -s u --description 'Look for the files to be uploaded in  upload-files-dir rather than  .'
complete -c dpkg-genbuildinfo -l always-include-kernel --description 'By default, the Build-Kernel-Version field will not be written out.'
complete -c dpkg-genbuildinfo -l always-include-path --description 'By default, the Build-Path field will only be written if the current director…'
complete -c dpkg-genbuildinfo -l admindir --description 'Change the location of the dpkg database.'
complete -c dpkg-genbuildinfo -s q --description 'dpkg-genbuildinfo might produce informative messages on standard error.'
complete -c dpkg-genbuildinfo -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-genbuildinfo -l version --description 'Show the version and exit.'

