# dpkg-distaddfile
# Autogenerated from man page /usr/share/man/man1/dpkg-distaddfile.1.gz
complete -c dpkg-distaddfile -s f --description 'Read or write the list of files to be uploaded here, rather than using  debia…'
complete -c dpkg-distaddfile -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-distaddfile -l version --description 'Show the version and exit.'

