# dpkg-checkbuilddeps
# Autogenerated from man page /usr/share/man/man1/dpkg-checkbuilddeps.1.gz
complete -c dpkg-checkbuilddeps -l admindir --description 'Change the location of the dpkg database (since dpkg 1. 14. 0).'
complete -c dpkg-checkbuilddeps -s A --description 'Ignore Build-Depends-Arch and Build-Conflicts-Arch lines (since dpkg 1. 16.'
complete -c dpkg-checkbuilddeps -s B --description 'Ignore Build-Depends-Indep and Build-Conflicts-Indep lines.'
complete -c dpkg-checkbuilddeps -s I --description 'Ignore built-in build depends and conflicts (since dpkg 1. 18. 2).'
complete -c dpkg-checkbuilddeps -s c --description 'Use the given build dependencies/conflicts instead of those contained in the …'
complete -c dpkg-checkbuilddeps -s a --description 'Check build dependencies/conflicts assuming that the package described in the…'
complete -c dpkg-checkbuilddeps -s P --description 'Check build dependencies/conflicts assuming that the package described in the…'
complete -c dpkg-checkbuilddeps -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-checkbuilddeps -s d --description '.'
complete -c dpkg-checkbuilddeps -l version --description 'Show the version and exit.'

