# dpkg-gencontrol
# Autogenerated from man page /usr/share/man/man1/dpkg-gencontrol.1.gz
complete -c dpkg-gencontrol -s v --description 'Sets the version number of the binary package which will be generated.'
complete -c dpkg-gencontrol -s V --description 'Set an output substitution variable.'
complete -c dpkg-gencontrol -s T --description 'Read substitution variables in R substvars-file ; the default is  debian/subs…'
complete -c dpkg-gencontrol -s D --description 'Override or add an output control file field.'
complete -c dpkg-gencontrol -s U --description 'Remove an output control file field.'
complete -c dpkg-gencontrol -s c --description 'Specifies the main source control file to read information from.'
complete -c dpkg-gencontrol -s l --description 'Specifies the changelog file to read information from.'
complete -c dpkg-gencontrol -s f --description 'Read or write the list of files to be uploaded here, rather than using  debia…'
complete -c dpkg-gencontrol -s F --description 'Specifies the format of the changelog.'
complete -c dpkg-gencontrol -s p --description 'Generate information for the binary package R package .'
complete -c dpkg-gencontrol -s n --description 'Assume the filename of the package will be  filename instead of the normal pa…'
complete -c dpkg-gencontrol -o is -o ip -o isp --description 'These options are ignored for compatibility with older versions of the dpkg b…'
complete -c dpkg-gencontrol -s P --description 'Tells  dpkg-source that the package is being built in  package-build-dir inst…'
complete -c dpkg-gencontrol -s O --description 'Print the control file to standard output (or filename if specified, since dp…'
complete -c dpkg-gencontrol -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-gencontrol -l version --description 'Show the version and exit.'

