# dpkg-query
# Autogenerated from man page /usr/share/man/man1/dpkg-query.1.gz
complete -c dpkg-query -l admindir --description 'Change the location of the dpkg database.'
complete -c dpkg-query -l load-avail --description 'Also load the available file when using the --show and --list commands, which…'
complete -c dpkg-query -l no-pager --description 'Disables the use of any pager when showing information (since dpkg 1. 19. 2).'
complete -c dpkg-query -s f -l showformat --description 'This option is used to specify the format of the output --show will produce (…'
complete -c dpkg-query -s l -l list --description 'List all known packages matching one or more patterns, regardless of their st…'
complete -c dpkg-query -s W -l show --description 'Just like the --list option this will list all packages matching the given pa…'
complete -c dpkg-query -s s -l status --description 'Report status of specified package.'
complete -c dpkg-query -s L -l listfiles --description 'List files installed to your system from package-name.'
complete -c dpkg-query -l control-list --description 'List control files installed to your system from package-name (since dpkg 1.'
complete -c dpkg-query -l control-show --description 'Print the control-file installed to your system from package-name to the stan…'
complete -c dpkg-query -s c -l control-path --description 'List paths for control files installed to your system from package-name (sinc…'
complete -c dpkg-query -s S -l search --description 'Search for packages that own files corresponding to the given pattern.'
complete -c dpkg-query -s p -l print-avail --description 'Display details about packages, as found in /var/lib/dpkg/available.'
complete -c dpkg-query -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-query -l version --description 'Show the version and exit.'

