# evince
# Autogenerated from man page /usr/share/man/man1/evince.1.gz
complete -c evince -s '?' -s h -l help --description 'Prints the command line options.'
complete -c evince -s p -l page-label --description 'Open the document on the page with the specified page label (or page number).'
complete -c evince -s i -l page-index --description 'Open the document on the page with the specified page index (this is the exac…'
complete -c evince -s n -l named-dest --description 'Open the document on the specified named destination.'
complete -c evince -s f -l fullscreen --description 'Run evince in fullscreen mode.'
complete -c evince -s s -l presentation --description 'Run evince in presentation mode.'
complete -c evince -s l -l find --description 'You can pass a word or phrase here.'
complete -c evince -s w -l preview --description 'Run evince as a previewer.'
complete -c evince -l unlink-temp-file --description 'If evince is run in preview mode, this will unlink the temporary file created…'
complete -c evince -l print-settings --description 'This sends the full path of the PDF file, f, and the settings of the print di…'

