# evince-previewer
# Autogenerated from man page /usr/share/man/man1/evince-previewer.1.gz
complete -c evince-previewer -s u -l unlink-tempfile --description 'Delete the temporary file.'
complete -c evince-previewer -s p -l print-settings --description 'Print settings file SEE ALSO evince(1), gnome-options(7), gtk-options(7).'

