# gnome-disks
# Autogenerated from man page /usr/share/man/man1/gnome-disks.1.gz
complete -c gnome-disks -l block-device --description 'Switches to the Disks application and selects the block device given by DEVIC…'
complete -c gnome-disks -l format-device -l xid --description 'Shows the \\(lqFormat Volume\\(rq dialog for the block device given by DEVICE (…'
complete -c gnome-disks -l restore-disk-image --description 'Shows the \\(lqRestore Disk Image\\(rq dialog for the file given by FILE (for e…'
complete -c gnome-disks -s h -l help --description 'Prints a short help text and exits.'

