# gnome-contacts
# Autogenerated from man page /usr/share/man/man1/gnome-contacts.1.gz
complete -c gnome-contacts -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gnome-contacts -s e -l email --description 'Show contact with this email address.'
complete -c gnome-contacts -s i -l individual --description 'Show contact with this individual id.'
complete -c gnome-contacts -s v -l version --description 'Show the current version of Contacts.'

