# gnome-control-center
# Autogenerated from man page /usr/share/man/man1/gnome-control-center.1.gz
complete -c gnome-control-center -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gnome-control-center -l version --description 'Prints the program version and exits.'
complete -c gnome-control-center -s v -l verbose --description 'Enables verbose mode.'
complete -c gnome-control-center -s l -l list --description 'Lists the available panels and exits.'
complete -c gnome-control-center -s o -l overview --description 'Opens the overview.'
complete -c gnome-control-center -s s -l search --description 'Sets the following search term.'

