# gnome-calculator
# Autogenerated from man page /usr/share/man/man1/gnome-calculator.1.gz
complete -c gnome-calculator -s e -l equation --description 'Start gnome-calculator and display the equation following this option.'
complete -c gnome-calculator -s s -l solve --description 'Solve the equation provided following this option.'
complete -c gnome-calculator -s v -l version --description 'Output version information and exit.'
complete -c gnome-calculator -s h -s '?' -l help --description 'Prints the command line options.  SEE ALSO gcalccmd.'

