# gnome-disk-image-mounter
# Autogenerated from man page /usr/share/man/man1/gnome-disk-image-mounter.1.gz
complete -c gnome-disk-image-mounter -l writable --description 'to change this.  RETURN VALUE.'

