# gnome-session-quit
# Autogenerated from man page /usr/share/man/man1/gnome-session-quit.1.gz
complete -c gnome-session-quit -l logout --description 'Prompt the user to confirm logout.  This is the default behavior.'
complete -c gnome-session-quit -l power-off --description 'Prompt the user to confirm system power off.'
complete -c gnome-session-quit -l reboot --description 'Prompt the user to confirm system reboot.'
complete -c gnome-session-quit -l force --description 'Ignore any inhibitors.'
complete -c gnome-session-quit -l no-prompt --description 'End the session without user interaction.  This only works with --logout.'

