# gnome-text-editor
# Autogenerated from man page /usr/share/man/man1/gnome-text-editor.1.gz
complete -c gnome-text-editor -l encoding --description 'Set the character encoding to be used for opening the files listed on the com…'
complete -c gnome-text-editor -l list-encodings --description 'Display list of possible values for the encoding option and exit.'
complete -c gnome-text-editor -l new-window --description 'Create a new toplevel window in an existing instance of  gedit.'
complete -c gnome-text-editor -l new-document --description 'Create a new document in an existing instance of  gedit.'
complete -c gnome-text-editor -s s -l standalone --description 'Run  gedit in standalone mode.'
complete -c gnome-text-editor -s w -l wait --description 'Open files and block the  gedit process.'
complete -c gnome-text-editor -l help --description 'Prints the command line options.'
complete -c gnome-text-editor -l version --description 'Output version information and exit.'

