# gnome-shell
# Autogenerated from man page /usr/share/man/man1/gnome-shell.1.gz
complete -c gnome-shell -s r -l replace --description 'Replace the running window manager.'
complete -c gnome-shell -l sm-disable --description 'Disable connection to the session manager.'
complete -c gnome-shell -l sm-client-id --description 'Specify session management ID.'
complete -c gnome-shell -l sm-save-file --description 'Initialize session from FILE.'
complete -c gnome-shell -l screen --description 'X screen to use.'
complete -c gnome-shell -s d -l display --description 'X Display to use.'
complete -c gnome-shell -l sync --description 'Make X calls synchronous.'
complete -c gnome-shell -l version --description 'Print version and exit.'
complete -c gnome-shell -l help --description 'Display help and exit.'
complete -c gnome-shell -l mode --description 'Use a specific mode, e. g.  "gdm" for login screen.'
complete -c gnome-shell -l list-modes --description 'List possible modes and exit.'
complete -c gnome-shell -l clutter-display --description 'Clutter the option display (otherwise ignored).'

