# gnome-language-selector
# Autogenerated from man page /usr/share/man/man1/gnome-language-selector.1.gz
complete -c gnome-language-selector -s h -l help --description 'show this help message and exit.'
complete -c gnome-language-selector -s n -l no-verify-installed-lang-support --description 'do not verify installed language support.'
complete -c gnome-language-selector -s d -l datadir --description 'use an alternative data directory instead of the default /usr/share/language-…'

