# gnome-session-inhibit
# Autogenerated from man page /usr/share/man/man1/gnome-session-inhibit.1.gz
complete -c gnome-session-inhibit -s h -l help --description 'print help and exit.'
complete -c gnome-session-inhibit -l version --description 'print version information and exit.'
complete -c gnome-session-inhibit -l app-id --description 'The application id to use when calling the gnome-session Inhibit() method.'
complete -c gnome-session-inhibit -l reason --description 'A human-readable reason to pass along when calling the gnome-session Inhibit(…'
complete -c gnome-session-inhibit -l inhibit --description 'ARG specifies the things to inhibit, as a colon-separated list.'
complete -c gnome-session-inhibit -l inhibit-only --description 'Do not launch COMMAND and wait forever instead.'

