# gnome-session
# Autogenerated from man page /usr/share/man/man1/gnome-session.1.gz
complete -c gnome-session -l autostart --description 'Start all applications defined in DIR, instead of starting the applications d…'
complete -c gnome-session -l session --description 'Use the applications defined in SESSION. session.  If not specified, gnome.'
complete -c gnome-session -l failsafe --description 'Run in fail-safe mode.  User-specified applications will not be started.'
complete -c gnome-session -l debug --description 'Enable debugging code.'
complete -c gnome-session -l whale --description 'Show the fail whale in a dialog for debugging it.'

