# gst-install
# Autogenerated from man page /usr/share/man/man1/gst-install.1.gz
complete -c gst-install -l transient-for --description 'The X Window ID of the window which should be used as parents for the dialogs…'

