# gst-launch-1
# Autogenerated from man page /usr/share/man/man1/gst-launch-1.0.1.gz
complete -c gst-launch-1 -l help --description 'Print help synopsis and available FLAGS.'
complete -c gst-launch-1 -s v -l verbose --description 'Output status information and property notifications.'
complete -c gst-launch-1 -s q -l quiet --description 'Do not print any progress information.'
complete -c gst-launch-1 -s m -l messages --description 'Output messages posted on the pipeline\'s bus.'
complete -c gst-launch-1 -s t -l tags --description 'Output tags (also known as metadata).'
complete -c gst-launch-1 -s e -l eos-on-shutdown --description 'Force an EOS event on sources before shutting the pipeline down.'
complete -c gst-launch-1 -s i -l index --description 'Gather and print index statistics.'
complete -c gst-launch-1 -s f -l no-fault --description 'Do not install a fault handler.'
complete -c gst-launch-1 -s T -l trace --description 'Print memory allocation traces.'

