# ibus-table-createdb
# Autogenerated from man page /usr/share/man/man1/ibus-table-createdb.1.gz
complete -c ibus-table-createdb -s n -l name --description 'database-file specifies the file name for the binary database for the IME.'
complete -c ibus-table-createdb -s s -l source --description 'source-file specifies the file which contains the source of the IME.'
complete -c ibus-table-createdb -s e -l extra --description 'extra-words-file specifies the file name for the extra words for the IME.'
complete -c ibus-table-createdb -s p -l pinyin --description 'pinyin-file specifies the source file for the pinyin.'
complete -c ibus-table-createdb -s o -l no-create-index --description 'Do not create an index for a database (Only for distribution purposes, a norm…'
complete -c ibus-table-createdb -s i -l create-index-only --description 'Only create an index for an existing database.'

