# mdig
# Autogenerated from man page /usr/share/man/man1/mdig.1.gz
complete -c mdig -s f --description 'option makes mdig operate in batch mode by reading a list of lookup requests …'
complete -c mdig -s h --description 'causes mdig to print the detailed help with the full list of options and exit.'
complete -c mdig -s v --description 'causes mdig to print the version number and exit.  GLOBAL OPTIONS.'
complete -c mdig -s 4 --description 'option forces mdig to only use IPv4 query transport.'
complete -c mdig -s 6 --description 'option forces mdig to only use IPv6 query transport.'
complete -c mdig -s b --description 'option sets the source IP address of the query to address.'
complete -c mdig -s m --description 'option enables memory usage debugging.'
complete -c mdig -s p --description 'option is used when a non-standard port number is to be queried.'
complete -c mdig -s c --description 'option sets the query class to class.'
complete -c mdig -s t --description 'option sets the query type to type.'
complete -c mdig -s x --description 'option is supplied to indicate a reverse lookup with the "PTR" query type.'

