# mutter
# Autogenerated from man page /usr/share/man/man1/mutter.1.gz
complete -c mutter -l display --description 'Connect to X display DISPLAY.'
complete -c mutter -l replace --description 'a window manager which is running is replaced by mutter.'
complete -c mutter -l sm-client-id --description 'Specify a session management ID.'
complete -c mutter -l sm-disable --description 'Disable the session management.'
complete -c mutter -l sm-save-file --description 'Load a session from FILENAME.'
complete -c mutter -l version --description 'Print the version number.'
complete -c mutter -s '?' -l help --description 'Show summary of options.'

