# orca
# Autogenerated from man page /usr/share/man/man1/orca.1.gz
complete -c orca -s s -l setup --description 'When starting  orca , initiate the GUI-based configuration.'
complete -c orca -s u -l user-prefs-dir --description 'When starting  orca , use  dirname as an alternate directory for the user pre…'
complete -c orca -s e -l enable --description 'When starting  orca , force the enabling of the supplied options.'
complete -c orca -s d -l disable --description 'When starting  orca , force the disabling of the supplied options.'
complete -c orca -s l -l list-apps --description 'Prints the names of all the currently running applications.'
complete -c orca -l debug --description 'Enables debug output for  orca and sends all debug output to a file with a na…'
complete -c orca -l debug-file --description 'Enables debug output for  orca and sends all debug output to the given filena…'
complete -c orca -s v -l version --description 'outputs  orca version number and exits.'
complete -c orca -s h -l help --description 'displays  orca help and exits.'
complete -c orca -l replace --description 'Replace a currently running  orca process.'

