# popsicle
# Autogenerated from man page /usr/share/man/man1/popsicle.1.gz
complete -c popsicle -s a -l all --description 'Flash all detected USB drives.'
complete -c popsicle -s c -l check --description 'Check written image matches read image.'
complete -c popsicle -s h -l help --description 'Prints help information.'
complete -c popsicle -s u -l unmount --description 'Unmount mounted devices.'
complete -c popsicle -s V -l version --description 'Prints version information.'
complete -c popsicle -s y -l yes --description 'Continue without confirmation . SS "ARGS:".'

