# request-key
# Autogenerated from man page /usr/share/man/man8/request-key.8.gz
complete -c request-key -s d --description 'Turn on debugging mode.'
complete -c request-key -s D --description 'In debugging mode, use the proposed key description specified with this rathe…'
complete -c request-key -s l --description 'Use configuration from the current directory.'
complete -c request-key -s n --description 'Don\'t log to the system log.'
complete -c request-key -s v --description 'Turn on debugging output.'
complete -c request-key -l version --description 'Print the program version and exit.'

