# system-config-printer
# Autogenerated from man page /usr/share/man/man1/system-config-printer.1.gz
complete -c system-config-printer -l help --description 'Display a short usage message.'
complete -c system-config-printer -l show-jobs --description 'Show the named print queue.'
complete -c system-config-printer -l debug --description 'Enable debugging output.'

