# totem-video-thumbnailer
# Autogenerated from man page /usr/share/man/man1/totem-video-thumbnailer.1.gz
complete -c totem-video-thumbnailer -s j -l jpeg --description 'Switch the output format to \\s-1JPEG. \\s0 The default is \\s-1PNG. \\s0.'
complete -c totem-video-thumbnailer -s l -l no-limit --description 'Don\'t limit the thumbnailing time to 30 seconds.  For debugging purposes.'

