# totem
# Autogenerated from man page /usr/share/man/man1/totem.1.gz
complete -c totem -s '?' -l help --description 'Output a longer help message then quit.'
complete -c totem -l version --description 'Output version information then quit.'
complete -c totem -l play-pause --description 'Tell an already-running instance of   Totem to toggle between play and pause.'
complete -c totem -l play --description 'Tell an already-running instance of  Totem to play (has no effect if already …'
complete -c totem -l pause --description 'Tell an already-running instance of  Totem to pause (has no effect if already…'
complete -c totem -l next --description 'Tell an already-running instance of   Totem to skip to the next movie or chap…'
complete -c totem -l previous --description 'Tell an already-running instance of   Totem to return to the previous movie o…'
complete -c totem -l seek-fwd --description 'Tell an already-running instance of   Totem to seek forwards 15 seconds in th…'
complete -c totem -l seek-bwd --description 'Tell an already-running instance of   Totem to seek backwards 15 seconds in t…'
complete -c totem -l volume-up --description 'Tell an already-running instance of   Totem to raise the volume by 8%.'
complete -c totem -l volume-down --description 'Tell an already-running instance of   Totem to lower the volume by 8%.'
complete -c totem -l mute --description 'Tell an already-running instance of   Totem to toggle between muted and unmut…'
complete -c totem -l fullscreen --description 'Tell an already-running instance of   Totem to toggle fullscreen mode.'
complete -c totem -l quit --description 'Tell an already-running instance of  Totem to quit.'
complete -c totem -l enqueue --description 'Tell an already-running instance of Totem to add a new stream to the playlist.'
complete -c totem -l replace --description 'Tell an already-running instance of Totem to play  from the playlist.'

