# tracker-tag
# Autogenerated from man page /usr/share/man/man1/tracker-tag.1.gz
complete -c tracker-tag -s t -l list --description 'List all tags.'
complete -c tracker-tag -s s -l show-files --description 'Show the files associated with each tag.'
complete -c tracker-tag -s a -l add --description 'Add a tag with the name TAG.'
complete -c tracker-tag -s d -l delete --description 'Delete a tag with the name TAG.'
complete -c tracker-tag -s e -l description --description 'This option ONLY applies when using  --add and provides a description to go w…'
complete -c tracker-tag -s l -l limit --description 'Limit search to N results.  The default is 512.'
complete -c tracker-tag -s o -l offset --description 'Offset the search results by N.'
complete -c tracker-tag -s r -l and-operator --description 'Use AND operator for search terms instead of OR (the default).'

