# tracker-info
# Autogenerated from man page /usr/share/man/man1/tracker-info.1.gz
complete -c tracker-info -s f -l full-namespaces --description 'By default, all keys and values reported about any given file are returned in…'
complete -c tracker-info -s c -l plain-text-content --description 'If the resource being displayed has nie:PlainTextContent (i. e.'
complete -c tracker-info -s i -l resource-is-iri --description 'In most cases, the file argument supplied points to a URL or PATH which is qu…'
complete -c tracker-info -s t -l turtle --description 'Output results as Turtle RDF.'

