# tracker-status
# Autogenerated from man page /usr/share/man/man1/tracker-status.1.gz
complete -c tracker-status -l stat --description 'By default, only common and useful classes are shown, e. g.'
complete -c tracker-status -s a -l all --description 'Display statistics about ALL RDF classes that exist in the database.'
complete -c tracker-status -l collect-debug-info --description 'Useful when debugging problems to diagnose the state of Tracker on your syste…'

