# tracker-miner-fs
# Autogenerated from man page /usr/share/man/man1/tracker-miner-fs.1.gz
complete -c tracker-miner-fs -s '?' -l help --description 'Show summary of options.'
complete -c tracker-miner-fs -s V -l version --description 'Returns the version of this binary.'
complete -c tracker-miner-fs -s v -l verbosity --description 'Sets the logging level, 0=errors, 1=minimal, 2=detailed, 3=debug.'
complete -c tracker-miner-fs -s s -l initial-sleep --description 'Sets the initial sleep time before crawling the file system is started.'
complete -c tracker-miner-fs -s n -l no-daemon --description 'Tells the miner to exit once all indexing has finished and the database is up…'
complete -c tracker-miner-fs -s e -l eligible --description 'Checks if  FILE  is eligible for being mined based on the current configurati…'

