# tracker-reset
# Autogenerated from man page /usr/share/man/man1/tracker-reset.1.gz
complete -c tracker-reset -s r -l hard --description 'This kills all processes in the same way that tracker daemon --kill does but …'
complete -c tracker-reset -s e -l soft --description 'A soft reset works exactly the same way that --hard does, with the exception …'
complete -c tracker-reset -s c -l config --description 'Resets all configuration to its defaults.'
complete -c tracker-reset -l kill --description 'tracker-store re-creates the databases.'
complete -c tracker-reset -s f -l file --description 'Resets all indexed information about FILE, works recursively for directories.'

