# tracker-store
# Autogenerated from man page /usr/share/man/man1/tracker-store.1.gz
complete -c tracker-store -s '?' -l help --description 'A brief help message including some examples.'
complete -c tracker-store -s V -l version --description 'Returns the version of this binary.'
complete -c tracker-store -s v -l verbosity --description 'Sets the logging level, 0=errors, 1=minimal, 2=detailed, 3=debug.'
complete -c tracker-store -s r -l force-reindex --description 'This forces tracker-store to remove databases and to recreate fresh databases…'
complete -c tracker-store -s n -l readonly-mode --description 'This starts tracker-store in a mode which disables writing to the database.'

