# tracker-sql
# Autogenerated from man page /usr/share/man/man1/tracker-sql.1.gz
complete -c tracker-sql -s f -l file --description 'Use a file with SPARQL content to query.'
complete -c tracker-sql -s q -l query --description 'Use a sql string to query the database with.'

