# tracker-index
# Autogenerated from man page /usr/share/man/man1/tracker-index.1.gz
complete -c tracker-index -s m -l reindex-mime-type -s m --description 'Re-index files which match the mime type supplied.'
complete -c tracker-index -s f -l index --description '(Re)index a file matching the file name(s) supplied.'
complete -c tracker-index -s b -l backup --description 'Begins backing up the Tracker databases and save it to the file given.'
complete -c tracker-index -s o -l restore --description 'Begins restoring a previous backup from the file which points to the location…'

