# tracker-extract
# Autogenerated from man page /usr/share/man/man1/tracker-extract.1.gz
complete -c tracker-extract -s v -l verbosity --description 'This sets the log verbosity for the extractor process.'
complete -c tracker-extract -s o -l output-format --description 'Choose which format to use to output results.'

