# tracker-sparql
# Autogenerated from man page /usr/share/man/man1/tracker-sparql.1.gz
complete -c tracker-sparql -s f -l file --description 'Use a file with SPARQL content to query or update.'
complete -c tracker-sparql -s q -l query --description 'Use a sparql string to query the database with.'
complete -c tracker-sparql -s u -l update --description 'This has to be used with --query.'
complete -c tracker-sparql -s c -l list-classes --description 'Returns a list of classes which describe the ontology used for storing data.'
complete -c tracker-sparql -s x -l list-class-prefixes --description 'Returns a list of classes and their related prefixes.'
complete -c tracker-sparql -s p -l list-properties --description 'Returns a list of properties which pertain to a class.'
complete -c tracker-sparql -s n -l list-notifies --description 'Returns a list of classes which are notified over D-Bus about any changes tha…'
complete -c tracker-sparql -s i -l list-indexes --description 'Returns a list of properties which are indexed in the database.'
complete -c tracker-sparql -s t -l tree --description 'Prints a tree showing all parent classes of class in the ontology.'
complete -c tracker-sparql -s s -l search --description 'Returns a list of classes and properties which partially match needle in the …'
complete -c tracker-sparql -l get-shorthand --description 'Returns the shorthand for a class given by a URL.  For example:  .'
complete -c tracker-sparql -l get-longhand --description 'example: $ tracker sparql -t nmo:MMSMessage ROOT   +-- rdfs:Resource (C)   | …'

