# ul
# Autogenerated from man page /usr/share/man/man1/ul.1.gz
complete -c ul -s i --description 'Underlining is indicated by a separate line containing appropriate dashes \\- …'
complete -c ul -s t --description 'Overrides the terminal type specified in the environment with terminal.'

