# x-session-manager
# Autogenerated from man page /usr/share/man/man1/x-session-manager.1.gz
complete -c x-session-manager -l autostart --description 'Start all applications defined in DIR, instead of starting the applications d…'
complete -c x-session-manager -l session --description 'Use the applications defined in SESSION. session.  If not specified, gnome.'
complete -c x-session-manager -l failsafe --description 'Run in fail-safe mode.  User-specified applications will not be started.'
complete -c x-session-manager -l debug --description 'Enable debugging code.'
complete -c x-session-manager -l whale --description 'Show the fail whale in a dialog for debugging it.'

