# xbrlapi
# Autogenerated from man page /usr/share/man/man1/xbrlapi.1.gz
complete -c xbrlapi -s b -l brlapi --description 'The  BrlAPI server to connect to.'
complete -c xbrlapi -s a -l auth --description 'The  BrlAPI authorization/authentication string.'
complete -c xbrlapi -s d -l display --description 'The  X display to connect to.'
complete -c xbrlapi -s q -l quiet --description 'Do not write any text to the braille device.'
complete -c xbrlapi -s h -l help --description 'Print a command line usage summary and then exit.'
complete -c xbrlapi -s H -l full-help --description 'Print a thorough command line usage summary and then exit.'

