height = 35
margin-top = 5
modules-left = [
    "sway/workspaces"
]
modules-right = [
  "idle_inhibitor",
  "pulseaudio",
  "cpu",
  "memory",
  "temperature",
  "backlight",
  "battery",
  "network",
  "tray",
  "clock"
]

["sway/workspaces"]
disable-scroll = true
all-outputs = true
format = "{name}: {icon}"

  ["sway/workspaces".format-icons]
  1 = ""
  2 = ""
  3 = ""
  4 = ""
  5 = ""
  urgent = ""
  focused = ""
  default = ""

  ["sway/workspaces".persistent_workspaces]
  1 = []
  2 = []
  3 = []
  4 = []
  5 = []

[idle_inhibitor]
format = "{icon}"

  [idle_inhibitor.format-icons]
  activated = ""
  deactivated = ""

[tray]
icon-size = 20
spacing = 10

[clock]
format = "{:%I:%M}"
format-alt = "{:%Y-%m-%d}"
tooltip-format = """
<big>{:%Y %B}</big>
<tt><small>{calendar}</small></tt>"""

[cpu]
format = "{usage}% "
tooltip = false

[memory]
format = "{}% "

[temperature]
critical-threshold = 80
format = "{temperatureC}°C {icon}"
format-icons = [ "", "", "" ]

[backlight]
format = "{percent}% {icon}"
format-icons = [ "", "" ]

[battery]
format = "{capacity}% {icon}"
format-charging = "{capacity}% "
format-plugged = "{capacity}% "
format-alt = "{time} {icon}"
format-icons = [ "", "", "", "", "" ]

  [battery.states]
  warning = 30
  critical = 15

["battery#bat2"]
bat = "BAT2"

[network]
format-wifi = "{essid} ({signalStrength}%) "
format-ethernet = "Connected  "
tooltip-format = "{ifname} via {gwaddr} "
format-linked = "{ifname} (No IP) "
format-disconnected = "Disconnected ⚠"
format-alt = "{ifname}: {ipaddr}/{cidr}"
on-click-right = "bash ~/.config/rofi/wifi_menu/rofi_wifi_menu"

[pulseaudio]
format = "{volume}% {icon} {format_source}"
format-bluetooth = "{volume}% {icon}"
format-bluetooth-muted = "{icon} {format_source}"
format-muted = "{format_source}"
format-source = "{volume}% "
format-source-muted = ""
on-click = "pavucontrol"

  [pulseaudio.format-icons]
  headphone = ""
  hands-free = ""
  headset = ""
  phone = ""
  portable = ""
  car = ""
  default = [ "", "", "" ]

["custom/media"]
format = "{icon} {}"
return-type = "json"
max-length = 20
escape = true
exec = "$HOME/.config/system_scripts/mediaplayer.py 2> /dev/null"
on-click = "playerctl play-pause"

  ["custom/media".format-icons]
  spotify = " "
  default = " "

["custom/launcher"]
format = ""
on-click = "rofi -show drun -theme ~/.config/rofi/wayfire/config2.rasi"
on-click-right = "killall rofi"

["custom/layout"]
format = " "
on-click = "bash ~/.config/system_scripts/layout.sh"

["custom/updater"]
format = "  {} Updates"
exec = "checkupdates | wc -l"
exec-if = "[[ $(checkupdates | wc -l) != 0 ]]"
interval = 15
on-click = "alacritty -e yay -Syu"
